language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -e .
  - python setup.py test
script:
  - pytest --cov=./
before_install:
  - pip install codecov pytest-cov pandas
after_success:
  - codecov
